language: node_js
node_js:
  - "11.0"
before_script:
  - npm install -g @angular/cli
script:
  - npm ci
  - npm run build:app
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master